//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System_DAL.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    
    public partial class devrimme_senaEntities : DbContext
    {
        public devrimme_senaEntities()
            : base("name=devrimme_senaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<About> About { get; set; }
        public DbSet<Admin> Admin { get; set; }
        public DbSet<Announcements> Announcements { get; set; }
        public DbSet<Author> Author { get; set; }
        public DbSet<Book> Book { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<Contact> Contact { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<Member> Member { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<Movement> Movement { get; set; }
        public DbSet<Punishment> Punishment { get; set; }
        public DbSet<Till> Till { get; set; }
    
        public virtual ObjectResult<string> MostBookAuthors()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MostBookAuthors");
        }
    }
}
