//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System_DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement
    {
        public int BookId;
        public int EmployeeId;
        public int MemberId;

        public Movement()
        {
            this.Punishment = new HashSet<Punishment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Book_Id { get; set; }
        public Nullable<int> Member_Id { get; set; }
        public Nullable<byte> Employee_Id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<System.DateTime> BringMemberDate { get; set; }
        public Nullable<bool> TransactionStatus { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<Punishment> Punishment { get; set; }
    }
}
