//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System_DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Till
    {
        public int Id { get; set; }
        public string Month { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
